---

# app_name, rpm_name and rpm_folder are standard variables, must be redefined for each role
# it allows re-usage of tasks

app_name:    'Talend AMC'
rpm_name:    'talend-amc'
rpm_folder:  'amc'
app_service: 'talend-amc'

##########################################################################
# AMC-specific configuration variables
# We will use "amc_" prefix in var names
##########################################################################

# Whether to install AMC into TAC (yes|no).
# When "yes":
#   - 'tac' role must be used in the playbook
#   - no separate systemd service talend-amc (as talend-tac service will be used instead)
#
# When "no":
#   - it does not depend on 'tac' role (but it still can be present in playbook)
#   - it will be installed as separate systemd service (talend-amc)
#   - in this case, tomcat selection variables (app_*) must be set properly below
#
# The recommended setting is to install AMC into TAC
#
 
amc_install_into_tac: "yes"


#####
# Tomcat-selection variables (actual only when amc_install_into_tac == "no", otherwise ignored)
#####

# This var shows whether we should use talend-tomcat in 'shared' mode (default settings)
app_use_talend_tomcat: "yes"      # allowed values are "yes" or "no"
app_tomcat_port:  "8080"          # tomcat_port is used only if tomcat_setup == "yes" (or when app_use_talend_tomcat == "yes")

# The following variables will be taken in account only if app_use_talend_tomcat == "no"
app_tomcat_home:  "/opt/tomcat"   # home folder for customer's tomcat
app_tomcat_mode:  "direct"        # can be one of "direct" or "shared"
app_tomcat_setup: "no"            # whether to update customer's tomcat configuration (ports)

#####
# Installation as systemd service (actual only when amc_install_into_tac == "no", otherwise ignored)
#####
app_install_systemd:  "yes"       # allowed values "yes" and "no"


#########################################
#
# Parameters below can be used for configuration updates (re-configuration) "on the fly"
#
#########################################

# There is no AMC-specific configuration options
