---

# This common script will be used to stop systemd service (if it exists,
#      as it might not exist on a new installation)
#
# Required role-level variable:
# - app_service (e.g. 'talend-tac') - systemd service name

- name: "Check systemd service status for {{ app_service }}"
  stat:
    path: "/etc/systemd/system/{{ app_service }}.service"
  register: systemd_service_file

- name: "Stop systemd service for {{ app_service }}"
  when: systemd_service_file.stat.exists
  shell: "systemctl stop {{ app_service }}.service"
