---

# Update SJS Configuration

- name: Update SJS server port
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'sjs_port=.*'
    replace: 'sjs_port={{ sjs_server_port }}'

- name: Update SJS host
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'sjs_host=.*'
    replace: 'sjs_host={{ sjs_host }}'

- name: Update SJS log directory
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'log_dir=.*'
    replace: 'log_dir={{ sjs_log_dir }}'

- name: Update SJS PID file
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'pidfile=.*'
    replace: 'pidfile={{ sjs_pidfile }}'

- name: Update SJS jobserver memory size
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'jobserver_memory=.*'
    replace: 'jobserver_memory={{ sjs_jobserver_memory }}'

- name: Update SJS context per jvm
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'context_per_jvm=.*'
    replace: 'context_per_jvm={{ sjs_context_per_jvm }}'

- name: Update SJS context per jvm
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'context_per_jvm=.*'
    replace: 'context_per_jvm={{ sjs_context_per_jvm }}'

- name: Update SJS database root directory
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'database_root_dir=.*'
    replace: 'database_root_dir={{ sjs_database_root_dir }}'

- name: Update SJS h2 tcp host
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'h2_tcp_host=.*'
    replace: 'h2_tcp_host={{ sjs_h2_tcp_host }}'

- name: Update SJS  h2 tcp port
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'h2_tcp_port=.*'
    replace: 'h2_tcp_port={{ sjs_h2_tcp_port }}'

- name: Update SJS deploy templates
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'deploy_templates=.*'
    replace: 'deploy_templates={{ sjs_deploy_templates }}'

- name: Update SJS datastreams deps jars
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'datastreams_deps_jars=.*'
    replace: 'datastreams_deps_jars={{ sjs_datastreams_deps_jars }}'

- name: Update SJS datastreams job jar
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'datastreams_job_jar=.*'
    replace: 'datastreams_job_jar={{ sjs_datastreams_job_jar }}'

- name: Update SJS spark home
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'spark_home=.*'
    replace: 'spark_home={{ sjs_spark_home }}'

- name: Update SJS spark conf dir
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'spark_conf_dir=.*'
    replace: 'spark_conf_dir={{ sjs_spark_conf_dir }}'

- name: Update SJS spark master
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'spark_master=.*'
    replace: 'spark_master={{ sjs_spark_master }}'

- name: Update SJS hadoop conf dir
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'hadoop_conf_dir=.*'
    replace: 'hadoop_conf_dir={{ sjs_hadoop_conf_dir }}'

- name: Update SJS yarn conf dir
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'yarn_conf_dir=.*'
    replace: 'yarn_conf_dir={{ sjs_yarn_conf_dir }}'

- name: Update SJS spark driver memory
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'spark_driver_memory=.*'
    replace: 'spark_driver_memory={{ sjs_spark_driver_memory }}'

- name: Update SJS krb5 config
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'krb5_config=.*'
    replace: 'krb5_config={{ sjs_krb5_config }}'

- name: Update SJS google application credentials
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'google_application_credentials=.*'
    replace: 'google_application_credentials={{ sjs_google_application_credentials }}'

- name: Update SJS jmx port
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'jmx_port=.*'
    replace: 'jmx_port={{ sjs_jmx_port }}'

- name: Update SJS sjs max direct memory
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'max_direct_memory=.*'
    replace: 'max_direct_memory={{ sjs_max_direct_memory }}'

- name: Update SJS  akka jvm exit on fatal error
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'akka_jvm_exit_on_fatal_error=.*'
    replace: 'akka_jvm_exit_on_fatal_error={{ sjs_akka_jvm_exit_on_fatal_error }}'

- name: Update SJS short timeout
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'short_timeout=.*'
    replace: 'short_timeout={{ sjs_short_timeout }}'

- name: Update SJS context creation timeout
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'context_creation_timeout=.*'
    replace: 'context_creation_timeout={{ sjs_context_creation_timeout }}'

- name: Update SJS yarn context creation timeout
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'yarn_context_creation_timeout=.*'
    replace: 'yarn_context_creation_timeout={{ sjs_yarn_context_creation_timeout }}'

- name: Update SJS default sync timeout
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'default_sync_timeout=.*'
    replace: 'default_sync_timeout={{ sjs_default_sync_timeout }}'

- name: Update SJS context init timeout
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'context_init_timeout=.*'
    replace: 'context_init_timeout={{ sjs_context_init_timeout }}'

- name: Update SJS spary request timeout
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'spary_request_timeout=.*'
    replace: 'spary_request_timeout={{ sjs_spary_request_timeout }}'

- name: Update SJS spray idle timeout
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'spray_idle_timeout=.*'
    replace: 'spray_idle_timeout={{ sjs_spray_idle_timeout }}'

- name: Update SJS dao ask timeout
  replace:
    path: "/etc/talend/sjs/settings.sh"
    regexp:  'dao_ask_timeout=.*'
    replace: 'dao_ask_timeout={{ sjs_dao_ask_timeout }}'










